version: "3.8"

services:
  db:
    container_name: postgres_workout_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: workout_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./seed_data.py:/docker-entrypoint-initdb.d/seed_data.py
      - ./data.json:/docker-entrypoint-initdb.d/data.json

volumes:
  pg_data:
